import Link from "next/link";
import Image from "next/image";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-300">
      {" "}
      <div className="max-w-4xl mx-auto px-6 py-16 md:px-10 md:py-24">
        {" "}
        <div className="text-center mb-16">
          {" "}
          <Image
            src="/logo/finwise-large-black1.png"
            alt="FinWise"
            width={260}
            height={70}
            className="mx-auto"
          />
          <h1 className="mt-6 text-5xl md:text-6xl font-bold text-white">
            Terms & Conditions
          </h1>
          <p className="mt-5 text-lg text-zinc-400 max-w-2xl mx-auto">
            These Terms & Conditions govern your access to and use of FinWise.
            By using the platform, you agree to these terms.
          </p>
          <p className="mt-6 text-sm text-zinc-500">
            Effective Date: 23 June 2026
          </p>
        </div>
        <div className="space-y-12 leading-8">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              1. Acceptance of Terms
            </h2>

            <p>
              By accessing or using FinWise, you agree to comply with and be
              bound by these Terms & Conditions and all applicable laws and
              regulations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              2. Platform Purpose
            </h2>

            <p>
              FinWise provides tools for financial tracking, invoice generation,
              tax estimation, expense management, reporting and related business
              productivity features.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              3. Informational Use Only
            </h2>

            <p>
              Information, calculations, estimates and reports generated by
              FinWise are provided for informational and organizational purposes
              only. Users should independently verify important financial, tax
              and compliance decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              4. User Responsibilities
            </h2>

            <p>
              Users are responsible for maintaining accurate information,
              protecting account credentials and ensuring compliance with
              applicable laws, regulations and filing requirements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              5. Account Security
            </h2>

            <p>
              Users are responsible for activities occurring under their
              accounts. FinWise should be notified promptly of any unauthorized
              access or suspected security issues.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              6. Intellectual Property
            </h2>

            <p>
              FinWise, including its software, branding, design, content, user
              interface and documentation, remains protected by applicable
              intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              7. Service Availability
            </h2>

            <p>
              While we strive to provide a reliable experience, we do not
              guarantee uninterrupted availability, error-free operation or
              permanent access to any feature.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              8. Account Termination
            </h2>

            <p>
              Users may delete their accounts through platform settings. FinWise
              reserves the right to suspend or terminate accounts involved in
              misuse, abuse, fraud or violations of these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              9. Updates to These Terms
            </h2>

            <p>
              We may update these Terms & Conditions periodically. Continued use
              of FinWise after updates constitutes acceptance of the revised
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              10. Contact
            </h2>

            <p>
              Questions regarding these Terms & Conditions may be directed to:
            </p>

            <p className="mt-4 text-emerald-400 font-medium">
              bansodekartik@hotmail.com
            </p>
          </section>
        </div>
        <div className="mt-20 pt-8 border-t border-zinc-800 text-center">
          <Link
            href="/"
            className="
        inline-flex
        items-center
        gap-2

        px-6 py-3

        rounded-xl

        border border-zinc-700
        bg-zinc-900

        text-white

        hover:bg-zinc-800
        transition
        "
          >
            ← Back to Home
          </Link>

          <p className="mt-6 text-sm text-zinc-500">
            © 2026 FinWise. All rights reserved.
          </p>
        </div>
      </div>
    </main>
  );
}
