export default function TermsPage() {
  return (
    <main className="ml-64 min-h-screen bg-gray-50 dark:bg-zinc-950 p-8 md:p-12">
      <div
        className="
max-w-5xl
mx-auto
bg-white dark:bg-zinc-900
border border-gray-200 dark:border-zinc-800
rounded-2xl
p-8 md:p-12
"
      >
        <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-3">
          Terms & Conditions
        </h1>
        <div className="mb-10 inline-flex items-center rounded-full bg-emerald-100 dark:bg-emerald-900/20 px-4 py-2 text-sm text-emerald-700 dark:text-emerald-400">
          FinWise India Legal Documentation
        </div>

        <p className="text-gray-500 dark:text-gray-400 mb-10">
          Effective Date: 17 June 2026
        </p>

        <div className="space-y-8 text-gray-700 dark:text-gray-300 leading-8">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              1. Acceptance of Terms
            </h2>

            <p>
              By accessing or using FinWise India, you agree to be bound by
              these Terms & Conditions and all applicable laws and regulations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              2. Platform Purpose
            </h2>

            <p>
              FinWise India provides tools for financial tracking, expense
              management, tax estimation, invoice generation, and financial
              analysis. The platform is intended for informational and
              organizational purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              3. No Professional Advice
            </h2>

            <p>
              FinWise India is not a Chartered Accountant, tax consultant,
              financial advisor, legal advisor, or registered investment
              advisor.
            </p>

            <p className="mt-3">
              Any tax calculations, financial projections, recommendations,
              insights, or reports generated by the platform should not be
              considered professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              4. User Responsibility
            </h2>

            <p>
              Users are solely responsible for verifying the correctness of
              information entered into the platform and for ensuring compliance
              with tax, accounting, and legal requirements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              5. Limitation of Liability
            </h2>

            <p>
              FinWise India and its creators shall not be liable for any direct,
              indirect, incidental, consequential, financial, tax-related, or
              business losses resulting from the use of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              6. Intellectual Property
            </h2>

            <p>
              FinWise India, including its source code, branding, design,
              content, user interface, and documentation, remains the
              intellectual property of FinWise India and its owner.
            </p>

            <p className="mt-3">
              Copying, redistribution, resale, cloning, reverse engineering, or
              commercial use without written permission is prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              7. Service Availability
            </h2>

            <p>
              We do not guarantee uninterrupted access, error-free operation, or
              continuous availability of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              8. Termination
            </h2>

            <p>
              We reserve the right to suspend or terminate accounts that violate
              these terms or misuse the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              9. Changes to Terms
            </h2>

            <p>
              FinWise India may modify these Terms & Conditions at any time.
              Continued use of the platform constitutes acceptance of revised
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
              10. Contact
            </h2>

            <p>For legal, licensing, or platform inquiries:</p>

            <p className="mt-3 font-medium text-emerald-600 dark:text-emerald-400">
              bansodekartik@hotmail.com
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
